### ISSUE TITLE
More picture posibility (camera, slideshow, per step)

### ISSUE THREAD

**Issue by Mannshoch** [mrzapp/nextcloud-cookbook#208]
We use the Cookbook app from Tablet. 
Please enhance the Picture possibilities

- [ ] Allow using the **Camera on Phone/Tablet** to add/replace a Picture
  - [ ] Enhance the supported file type with video and allow to add a Link instead of a file #206
- [ ] Allow adding more than one Picture and because of that add a slideshow (no auto slide) #187 
- [ ] Allow adding at least one Picture per step #47 

[Edit] 
After forming my Idea and read again the issues I found several Ideas that fit into this subject. So I added them here.

**Comment by hitam4450** [comment]
I agree!

**Comment by mrzapp** [comment]
Closing as duplicate of #47
